import { describe, it, expect, vi, beforeEach } from 'vitest'
import { createPinia, setActivePinia } from 'pinia'
import { getCurrentUser } from 'aws-amplify/auth'
import { listOpenRequestsWithClinic } from '@/graphql/custom-queries'

// Regression / integration coverage for the "matching engine silently finds
// nothing" bug fixed on this branch (commit 82c8d44). Three independent breaks
// combined to make searchMatches() never return a match even with perfectly
// compatible mock data:
//   1. useOwnerProfile() was destructured as `ownerProfile` but the composable
//      actually exports `form` -> ownerProfile.value was always undefined.
//   2. The `if (!ownerProfile.value) await fetchProfile()` guard could never
//      fire because `form` defaults to a non-null object -> profile (lat/long)
//      was never actually fetched even after fixing (1).
//   3. listRequests (the Amplify-generated query) only selected `clinicID`,
//      not the nested `clinic` object, so the geo filter's
//      `req.clinic.latitude`/`longitude` read was always undefined -> every
//      Request was dropped by the distance check.
//
// Bug (3) was first "fixed" by hand-editing the generated src/graphql/queries.js
// directly -- but that file is regenerated by `amplify codegen`/`amplify push`
// (see its own header comment), which would have silently wiped the fix on the
// next codegen run and reintroduced the bug with no failing test to catch it,
// since a test only sees whatever query string is checked into git. Moved to a
// new custom query, listOpenRequestsWithClinic in custom-queries.js, following
// this codebase's existing pattern for hand-written queries that need fields
// beyond default codegen output (see getVetWithClinic in the same file) --
// that file is never touched by codegen.
//
// These tests exercise the full chain with a mocked `generateClient().graphql`
// and assert an actual Match comes out the other end, not just "doesn't throw".

const graphqlMock = vi.fn()

vi.mock('aws-amplify/api', () => ({
  generateClient: () => ({ graphql: graphqlMock }),
}))

vi.mock('aws-amplify/auth', () => ({
  getCurrentUser: vi.fn(async () => ({ userId: 'owner-1' })),
}))

// useOwnerProfile() calls useRouter() (only exercised by deleteAccount, which
// we never call here) — stub it out so the composable can be used outside of
// an actual mounted component / router instance.
vi.mock('vue-router', () => ({
  useRouter: () => ({ push: vi.fn() }),
}))

// useOwnerProfile() also calls useAuthStore(), whose module imports the real
// `@/router` singleton (createRouter(...) + every route-level view component)
// purely for its `login`/`logout` helpers we never exercise here — stub it out
// so importing the store doesn't drag in the whole app's router/view graph.
vi.mock('@/router', () => ({
  default: { push: vi.fn() },
}))

import { useMatchingRequests } from '@/composables/useMatchingRequests'

// Paris (siège de la clinique dans nos fixtures)
const CLINIC_LAT = 48.8566
const CLINIC_LON = 2.3522
// ~2km de la clinique
const OWNER_LAT = 48.87
const OWNER_LON = 2.36

const buildOwnerProfile = (overrides = {}) => ({
  id: 'owner-1',
  firstname: 'Jean',
  lastname: 'Dupont',
  email: 'jean.dupont@example.com',
  phone: '0600000000',
  address: '1 rue de Paris',
  latitude: OWNER_LAT,
  longitude: OWNER_LON,
  maxTravelDistance: 50,
  ...overrides,
})

// Un an dans le futur, calculé relativement à "maintenant" pour ne pas pourrir
// avec le temps (checkEligibility utilise `now = new Date()` par défaut).
const ONE_YEAR_MS = 365 * 24 * 60 * 60 * 1000
const FUTURE_VALIDATION_EXPIRY = new Date(Date.now() + ONE_YEAR_MS).toISOString()

const buildAnimal = (overrides = {}) => ({
  id: 'animal-1',
  name: 'Rex',
  species: 'DOG',
  breed: 'Labrador',
  birthDate: '2020-01-01',
  weight: 25,
  bloodGroup: 'DEA 1.1-',
  isVaccinated: true,
  isSterilized: true,
  donationFrequency: 'TWICE_YEAR',
  // Requis par checkEligibility (critère 1, isValidatedDonor) et critère 3
  // (satisfiesFrequencyRule) -- voir src/services/eligibility-service.js.
  // Ces champs manquaient dans listMyAnimalsByOwnerId avant ce fix, ce qui
  // aurait fait échouer silencieusement le critère 1 (undefined n'est jamais
  // Validated Donor) : le fixture les fournit désormais explicitement, comme
  // le fait la query réelle une fois étendue (custom-queries.js).
  isValidatedDonor: true,
  validationExpiresAt: FUTURE_VALIDATION_EXPIRY,
  lastDonationDate: null,
  ownerID: 'owner-1',
  createdAt: '2024-01-01T00:00:00.000Z',
  ...overrides,
})

const buildRequest = (overrides = {}) => ({
  id: 'request-1',
  requiredSpecies: 'DOG',
  requiredBloodGroup: 'DEA 1.1-',
  requestType: 'EMERGENCY',
  status: 'OPEN',
  createdAt: '2024-01-01T00:00:00.000Z',
  clinicID: 'clinic-1',
  clinic: {
    id: 'clinic-1',
    name: 'Clinique du Centre',
    latitude: CLINIC_LAT,
    longitude: CLINIC_LON,
  },
  activeMissionID: null,
  updatedAt: '2024-01-01T00:00:00.000Z',
  ...overrides,
})

/**
 * Routes the mocked graphql client to the right fixture based on the
 * operation name embedded in the query string, mirroring what
 * useOwnerProfile.fetchProfile / useAnimals.fetchAnimals / useMatchingRequests
 * actually call.
 *
 * `clinicRelations` defaults to `[]` — most tests don't care about Clinic
 * Priority (critère 5) and must keep behaving exactly as before this was
 * wired in (regression coverage, see the dedicated `describe` block below).
 */
function mockGraphqlResponses({ profile, animals, requests, clinicRelations = [] }) {
  graphqlMock.mockImplementation(async ({ query }) => {
    if (query.includes('GetOwner')) {
      return { data: { getOwner: profile } }
    }
    if (query.includes('ListMyAnimalsByOwnerId')) {
      return { data: { listAnimals: { items: animals } } }
    }
    if (query.includes('MyClinicRelationsByOwnerID')) {
      return { data: { clinicOwnerRelationsByOwnerID: { items: clinicRelations } } }
    }
    if (query.includes('ListOpenRequestsWithClinic')) {
      return { data: { listRequests: { items: requests } } }
    }
    throw new Error(`Unexpected graphql call in test: ${query.slice(0, 60)}`)
  })
}

describe('useMatchingRequests', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
    graphqlMock.mockReset()
    // Réinitialise explicitement à chaque test la valeur par défaut ('owner-1',
    // celle utilisée par toutes les fixtures ci-dessus) : ce module mock n'a pas
    // `restoreMocks`/`clearMocks` activé dans vitest.config.js, et un test qui
    // reconfigure getCurrentUser() (voir describe Clinic Priority ci-dessous) ne
    // doit pas laisser fuiter cette valeur vers les tests suivants.
    vi.mocked(getCurrentUser).mockResolvedValue({ userId: 'owner-1' })
  })

  // Pin la définition réelle de la query (pas le mock) : si `clinic { ... }`
  // est un jour retiré de listOpenRequestsWithClinic (régression du bug #3),
  // ce test échoue même si les fixtures mockées ci-dessous continuent, elles,
  // d'injecter `clinic` à la main. Contrairement à l'ancienne version de ce
  // test (qui pinnait le listRequests généré par Amplify codegen), cette
  // query vit dans custom-queries.js, jamais régénérée par codegen -- le
  // pin reste donc valable après un `amplify push` réel, pas seulement sur
  // le code source tel qu'actuellement commité.
  it('la query listOpenRequestsWithClinic sélectionne bien l\'objet clinic imbriqué', () => {
    expect(listOpenRequestsWithClinic).toContain('clinic {')
    expect(listOpenRequestsWithClinic).toContain('latitude')
    expect(listOpenRequestsWithClinic).toContain('longitude')
  })

  it('trouve un Match réel de bout en bout (profil + animal compatible + clinique proche)', async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [buildAnimal()],
      requests: [buildRequest()],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    // La preuve que fetchProfile() a bien été appelé (bug #1 et #2) : getOwner
    // a été requêté.
    expect(graphqlMock).toHaveBeenCalledWith(
      expect.objectContaining({ query: expect.stringContaining('GetOwner') }),
    )

    expect(matches.value).toHaveLength(1)
    expect(matches.value[0].id).toBe('request-1')
    // La preuve que la clinique imbriquée a bien été sélectionnée (bug #3) :
    // le filtre géographique a pu attacher une distance calculée.
    expect(matches.value[0].distanceKM).toBeTypeOf('number')
    expect(matches.value[0].distanceKM).toBeLessThan(50)
    expect(matches.value[0].matchingAnimal.id).toBe('animal-1')
  })

  it('exclut une Request hors du rayon maxTravelDistance', async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile({ maxTravelDistance: 50 }),
      animals: [buildAnimal()],
      requests: [
        buildRequest({
          id: 'request-far',
          clinic: { id: 'clinic-far', name: 'Clinique lointaine', latitude: 45.764, longitude: 4.8357 }, // Lyon, ~390km de Paris
        }),
      ],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(0)
  })

  it("exclut une Request dont l'espèce ou le groupe sanguin ne correspond à aucun animal du propriétaire", async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [buildAnimal({ species: 'CAT', bloodGroup: 'A' })],
      requests: [buildRequest({ requiredSpecies: 'DOG', requiredBloodGroup: 'DEA 1.1-' })],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(0)
  })

  it("s'arrête sans appeler listRequests si le propriétaire n'a aucun animal", async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [],
      requests: [buildRequest()],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(0)
    expect(graphqlMock).not.toHaveBeenCalledWith(
      expect.objectContaining({ query: expect.stringContaining('ListRequests') }),
    )
  })

  // Cette régression n'existait PAS avant ce fix : searchMatches() filtrait
  // uniquement sur la géo puis `.find(isBloodCompatible)`, sans jamais
  // consulter isValidatedDonor/validationExpiresAt (critère 1 de
  // l'Eligibility, CONTEXT.md). Un animal non-validé, ou dont la validation
  // a expiré, aurait donc été proposé comme match sur `main`, alors même que
  // son groupe sanguin et la distance étaient parfaitement compatibles. Ce
  // test aurait échoué sur `main` (matches.value aurait eu 1 élément).
  it("exclut une Request si l'unique animal compatible n'est pas (ou plus) un Validated Donor", async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [buildAnimal({ isValidatedDonor: false })],
      requests: [buildRequest()],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(0)
  })

  it('exclut une Request si la validation Donor de l\'unique animal compatible a expiré', async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [
        buildAnimal({
          isValidatedDonor: true,
          validationExpiresAt: '2020-01-01T00:00:00.000Z', // expirée depuis longtemps
        }),
      ],
      requests: [buildRequest()],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(0)
  })

  // Même constat que ci-dessus pour la Frequency Rule (critère 3) : l'ancienne
  // version de searchMatches() ne consultait ni lastDonationDate ni
  // donationFrequency. Un animal ayant donné il y a 5 jours avec une
  // TWICE_YEAR (minimum 182 jours, cf. MIN_DAYS_BETWEEN_DONATIONS) serait
  // ressorti comme match sur `main`. Ce test aurait échoué sur `main`.
  it("exclut une Request si l'unique animal compatible a donné trop récemment (Frequency Rule)", async () => {
    const fiveDaysAgo = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString()

    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [
        buildAnimal({
          donationFrequency: 'TWICE_YEAR',
          lastDonationDate: fiveDaysAgo,
        }),
      ],
      requests: [buildRequest()],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(0)
  })

  // La boucle de useMatchingRequests.searchMatches() est un `for...of` classique
  // (pas un `.find()`/`.some()` qui s'arrêterait sur le premier animal testé,
  // qu'il soit éligible ou non) : si le premier animal du propriétaire échoue
  // un critère de l'Eligibility, le deuxième doit quand même être évalué et,
  // s'il est éligible, faire matcher la Request. Un refactor qui réintroduirait
  // un `.find(animal => checkEligibility(...).eligible)` court-circuiterait
  // silencieusement sur le premier animal et exclurait à tort toute la Request
  // dès que le premier animal listé n'est pas le bon donneur.
  it("matche la Request avec le deuxième animal du propriétaire quand le premier échoue un critère d'Eligibility", async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [
        buildAnimal({ id: 'animal-not-donor', isValidatedDonor: false }),
        buildAnimal({ id: 'animal-eligible' }),
      ],
      requests: [buildRequest()],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(1)
    expect(matches.value[0].matchingAnimal.id).toBe('animal-eligible')
    // distanceKM doit provenir du checkEligibility() de l'animal réellement
    // éligible (animal-eligible), pas rester `null`/`undefined` comme le
    // renvoie checkEligibility() pour l'animal non-donneur testé en premier
    // (NOT_VALIDATED_DONOR court-circuite avant le calcul de distance, cf.
    // eligibility-service.js) -- preuve qu'aucune valeur périmée d'un animal
    // précédemment testé ne "fuit" sur le résultat final.
    expect(matches.value[0].distanceKM).toBeTypeOf('number')
    expect(matches.value[0].distanceKM).toBeGreaterThan(0)
    expect(matches.value[0].distanceKM).toBeLessThan(50)
  })

  it('trie les Matches par distance croissante', async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile({ maxTravelDistance: 500 }),
      animals: [buildAnimal()],
      requests: [
        buildRequest({
          id: 'request-far',
          clinic: { id: 'clinic-b', name: 'B', latitude: 45.764, longitude: 4.8357 }, // Lyon
        }),
        buildRequest({
          id: 'request-near',
          clinic: { id: 'clinic-a', name: 'A', latitude: CLINIC_LAT, longitude: CLINIC_LON }, // Paris, proche
        }),
      ],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value.map((m) => m.id)).toEqual(['request-near', 'request-far'])
  })

  // Critère 5 de l'Eligibility (Clinic Priority, CONTEXT.md) : jusqu'à ce fix,
  // searchMatches() appelait toujours checkEligibility() avec ownerClinicIds
  // resté à sa valeur par défaut ([]) -> hasClinicPriority était toujours
  // false et ce critère n'affectait jamais rien de visible pour l'Owner.
  describe('Clinic Priority (critère 5)', () => {
    it("interroge myClinicRelationsByOwnerID avec l'ownerID de getCurrentUser(), pas une valeur en dur", async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile(),
        animals: [buildAnimal()],
        requests: [buildRequest()],
        clinicRelations: [],
      })

      const { searchMatches } = useMatchingRequests()

      await searchMatches()

      expect(graphqlMock).toHaveBeenCalledWith(
        expect.objectContaining({
          query: expect.stringContaining('MyClinicRelationsByOwnerID'),
          variables: { ownerID: 'owner-1' },
        }),
      )
    })

    // Renforce le test précédent : toutes les fixtures de ce fichier utilisent
    // 'owner-1' aussi bien comme userId (mock getCurrentUser) que comme id de
    // profil (buildOwnerProfile), donc un code qui écrirait `ownerID: 'owner-1'`
    // en dur au lieu de lire `userId` depuis getCurrentUser() passerait quand
    // même le test ci-dessus par coïncidence. Ici, getCurrentUser() renvoie
    // délibérément un userId QUI NE CORRESPOND À AUCUNE fixture ('owner-42') :
    // seule une vraie lecture de getCurrentUser().userId peut faire matcher
    // cette assertion.
    it("propage le userId réel de getCurrentUser(), pas la valeur 'owner-1' qui apparaît par ailleurs dans les fixtures", async () => {
      vi.mocked(getCurrentUser).mockResolvedValue({ userId: 'owner-42' })

      mockGraphqlResponses({
        profile: buildOwnerProfile(),
        animals: [buildAnimal()],
        requests: [buildRequest()],
        clinicRelations: [],
      })

      const { searchMatches } = useMatchingRequests()

      await searchMatches()

      expect(graphqlMock).toHaveBeenCalledWith(
        expect.objectContaining({
          query: expect.stringContaining('MyClinicRelationsByOwnerID'),
          variables: { ownerID: 'owner-42' },
        }),
      )
    })

    // La preuve du GROUPEMENT (lecture (1) retenue, voir le commentaire dans
    // useMatchingRequests.searchMatches) : une Request plus ÉLOIGNÉE mais liée à une
    // Clinic déjà connue de l'Owner doit malgré tout sortir AVANT une Request plus proche
    // mais sans relation existante -- pas seulement à égalité de distance (lecture (2),
    // rejetée).
    it("fait remonter en tête une Request liée à une Clinic déjà connue de l'Owner, même si elle est plus loin qu'une autre Request compatible", async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile({ maxTravelDistance: 500 }),
        animals: [buildAnimal()],
        requests: [
          buildRequest({
            id: 'request-near-unknown-clinic',
            clinic: { id: 'clinic-unknown', name: 'Inconnue', latitude: CLINIC_LAT, longitude: CLINIC_LON }, // Paris, très proche
          }),
          buildRequest({
            id: 'request-far-known-clinic',
            clinic: { id: 'clinic-known', name: 'Connue', latitude: 45.764, longitude: 4.8357 }, // Lyon, loin
          }),
        ],
        clinicRelations: [{ clinicID: 'clinic-known' }],
      })

      const { matches, searchMatches } = useMatchingRequests()

      await searchMatches()

      expect(matches.value.map((m) => m.id)).toEqual([
        'request-far-known-clinic',
        'request-near-unknown-clinic',
      ])
      expect(matches.value[0].hasClinicPriority).toBe(true)
      expect(matches.value[1].hasClinicPriority).toBe(false)
    })

    // Cas réaliste avec PLUSIEURS Requests de chaque côté (2 avec Clinic Priority, 2 sans),
    // à distances volontairement entremêlées -- pas seulement 2 Requests comme le test
    // ci-dessus. C'est le cas le plus susceptible de démasquer un comparateur bugué qui ne
    // gérerait correctement qu'une comparaison à 2 éléments (ex. un simple `if (a.has) return
    // -1` sans gérer le groupe symétrique, ou un comparateur non transitif) mais casserait
    // sous le tri multi-éléments réel d'Array.prototype.sort : ici, une Request non-priority
    // TRÈS proche (0km, plus proche que tout le reste) doit malgré tout finir APRÈS les deux
    // Requests priority, y compris la plus lointaine d'entre elles (~390km).
    it('avec plusieurs Requests des deux côtés, TOUTES les Requests Clinic Priority sortent avant TOUTES les autres, quelle que soit leur distance individuelle', async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile({ maxTravelDistance: 1000 }),
        animals: [buildAnimal()],
        requests: [
          // Volontairement pas déjà triées par distance dans le tableau d'entrée : le tri
          // doit reposer sur le comparateur, pas sur un ordre d'entrée qui masquerait un bug.
          buildRequest({
            id: 'request-nonpriority-farthest',
            clinic: { id: 'clinic-marseille', name: 'Marseille', latitude: 43.2965, longitude: 5.3698 }, // ~660km
          }),
          buildRequest({
            id: 'request-priority-close',
            clinic: { id: 'clinic-known-close', name: 'Paris (connue)', latitude: CLINIC_LAT, longitude: CLINIC_LON }, // ~2km
          }),
          buildRequest({
            id: 'request-nonpriority-veryclose',
            clinic: { id: 'clinic-unknown-veryclose', name: 'Inconnue (très proche)', latitude: OWNER_LAT, longitude: OWNER_LON }, // ~0km
          }),
          buildRequest({
            id: 'request-priority-far',
            clinic: { id: 'clinic-known-far', name: 'Lyon (connue)', latitude: 45.764, longitude: 4.8357 }, // ~390km
          }),
        ],
        clinicRelations: [{ clinicID: 'clinic-known-close' }, { clinicID: 'clinic-known-far' }],
      })

      const { matches, searchMatches } = useMatchingRequests()

      await searchMatches()

      // Groupement primaire (priority d'abord, en bloc), distance croissante au sein de
      // chaque groupe -- 'request-nonpriority-veryclose' (0km, la plus proche de TOUTES)
      // finit malgré tout après 'request-priority-far' (~390km).
      expect(matches.value.map((m) => m.id)).toEqual([
        'request-priority-close',
        'request-priority-far',
        'request-nonpriority-veryclose',
        'request-nonpriority-farthest',
      ])
      expect(matches.value.slice(0, 2).every((m) => m.hasClinicPriority === true)).toBe(true)
      expect(matches.value.slice(2).every((m) => m.hasClinicPriority === false)).toBe(true)
    })

    // Régression : sans aucune ClinicOwnerRelation existante pour cet Owner (cas normal
    // pour un nouvel Owner), le tri doit rester purement par distance -- comme avant ce
    // fix, et comme le garantit déjà 'trie les Matches par distance croissante' ci-dessus
    // (clinicRelations: [] par défaut). Ce test le rend explicite pour Clinic Priority.
    it('sans aucune ClinicOwnerRelation, trie toujours par distance seule', async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile({ maxTravelDistance: 500 }),
        animals: [buildAnimal()],
        requests: [
          buildRequest({
            id: 'request-far',
            clinic: { id: 'clinic-b', name: 'B', latitude: 45.764, longitude: 4.8357 }, // Lyon
          }),
          buildRequest({
            id: 'request-near',
            clinic: { id: 'clinic-a', name: 'A', latitude: CLINIC_LAT, longitude: CLINIC_LON }, // Paris, proche
          }),
        ],
        clinicRelations: [],
      })

      const { matches, searchMatches } = useMatchingRequests()

      await searchMatches()

      expect(matches.value.map((m) => m.id)).toEqual(['request-near', 'request-far'])
      expect(matches.value.every((m) => m.hasClinicPriority === false)).toBe(true)
    })
  })
})
