import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { createPinia, setActivePinia } from 'pinia'
import { getCurrentUser } from 'aws-amplify/auth'

// Regression / integration coverage for the "matching engine silently finds
// nothing" bug fixed on this branch (commit 82c8d44). Three independent breaks
// combined to make searchMatches() never return a match even with perfectly
// compatible mock data:
//   1. useOwnerProfile() was destructured as `ownerProfile` but the composable
//      actually exports `form` -> ownerProfile.value was always undefined.
//   2. The `if (!ownerProfile.value) await fetchProfile()` guard could never
//      fire because `form` defaults to a non-null object -> profile (lat/long)
//      was never actually fetched even after fixing (1).
//   3. listRequests (the Amplify-generated query) only selected `clinicID`,
//      not the nested `clinic` object, so the geo filter's
//      `req.clinic.latitude`/`longitude` read was always undefined -> every
//      Request was dropped by the distance check.
//
// Bug (3) was first "fixed" by hand-editing the generated src/graphql/queries.js
// directly -- but that file is regenerated by `amplify codegen`/`amplify push`
// (see its own header comment), which would have silently wiped the fix on the
// next codegen run and reintroduced the bug with no failing test to catch it,
// since a test only sees whatever query string is checked into git. Moved to a
// new custom query, listOpenRequestsWithClinic in custom-queries.js (Gen1 --
// since superseded by the Gen2 `selectionSet` covered below), following this
// codebase's existing pattern for hand-written queries that need fields beyond
// default codegen output (see getVetWithClinic in the same file) -- that file
// is never touched by codegen.
//
// These tests exercise the full chain with a mocked Gen2 client and assert an
// actual Match comes out the other end, not just "doesn't throw".

// Phase 8, sous-tâche 5 (lot 3/3, le dernier) : useMatchingRequests.js migré intégralement
// sur le client Gen2 (`aws-amplify/data`, `client.models.*`) -- ses 2 derniers appels propres
// (`myClinicRelationsByOwnerID`/`listOpenRequestsWithClinic`, Gen1 `client.graphql(...)`) sont
// désormais `client.models.ClinicOwnerRelation.list()`/`client.models.Request.list()`, comme
// les 3 branches migrées en lot 1 (`Owner.get`/`Animal.list`/`OwnerAvailability.list`, via
// useOwnerProfile()/useAnimals()/useOwnerAvailability() instanciés en interne).
//
// Décision (mock `.graphql` retiré) : `graphqlMock`/`vi.mock('aws-amplify/api', ...)`
// existaient uniquement pour ces 2 appels -- vérifié qu'aucun autre composable exercé par ce
// fichier (useAnimals/useOwnerProfile/useOwnerAvailability, tous migrés depuis le lot 1)
// n'utilise plus `aws-amplify/api`/`client.graphql()`. Le mock devenait donc entièrement mort
// une fois ces 2 derniers appels migrés -- retiré plutôt que laissé par prudence (choix
// documenté dans le rapport de cette sous-tâche : décision explicitement laissée ouverte par
// le brief, tranchée ici après vérification qu'aucun test de ce fichier n'en dépend plus).
// `vi.hoisted()` reste nécessaire (même raison qu'avant : `mockGenerateClient` ferme sur des
// mocks non triviaux, non couverts par l'heuristique de hoisting "légère" de Vitest).
const { ownerGetMock, animalListMock, availabilityListMock, relationListMock, requestListMock, mockGenerateClient } =
  vi.hoisted(() => {
    const ownerGetMock = vi.fn()
    const animalListMock = vi.fn()
    const availabilityListMock = vi.fn()
    const relationListMock = vi.fn()
    const requestListMock = vi.fn()
    const mockGenerateClient = () => ({
      models: {
        Owner: { get: (...args) => ownerGetMock(...args) },
        Animal: { list: (...args) => animalListMock(...args) },
        OwnerAvailability: { list: (...args) => availabilityListMock(...args) },
        ClinicOwnerRelation: { list: (...args) => relationListMock(...args) },
        Request: { list: (...args) => requestListMock(...args) },
      },
    })
    return {
      ownerGetMock,
      animalListMock,
      availabilityListMock,
      relationListMock,
      requestListMock,
      mockGenerateClient,
    }
  })

vi.mock('aws-amplify/data', () => ({
  generateClient: mockGenerateClient,
}))

vi.mock('aws-amplify/auth', () => ({
  getCurrentUser: vi.fn(async () => ({ userId: 'owner-1' })),
}))

// useOwnerProfile() calls useRouter() (only exercised by deleteAccount, which
// we never call here) — stub it out so the composable can be used outside of
// an actual mounted component / router instance.
vi.mock('vue-router', () => ({
  useRouter: () => ({ push: vi.fn() }),
}))

// useOwnerProfile() also calls useAuthStore(), whose module imports the real
// `@/router` singleton (createRouter(...) + every route-level view component)
// purely for its `login`/`logout` helpers we never exercise here — stub it out
// so importing the store doesn't drag in the whole app's router/view graph.
vi.mock('@/router', () => ({
  default: { push: vi.fn() },
}))

import { useMatchingRequests } from '@/composables/useMatchingRequests'

// Paris (siège de la clinique dans nos fixtures)
const CLINIC_LAT = 48.8566
const CLINIC_LON = 2.3522
// ~2km de la clinique
const OWNER_LAT = 48.87
const OWNER_LON = 2.36

const buildOwnerProfile = (overrides = {}) => ({
  id: 'owner-1',
  firstname: 'Jean',
  lastname: 'Dupont',
  email: 'jean.dupont@example.com',
  phone: '0600000000',
  address: '1 rue de Paris',
  latitude: OWNER_LAT,
  longitude: OWNER_LON,
  maxTravelDistance: 50,
  ...overrides,
})

// Un an dans le futur, calculé relativement à "maintenant" pour ne pas pourrir
// avec le temps (checkEligibility utilise `now = new Date()` par défaut).
const ONE_YEAR_MS = 365 * 24 * 60 * 60 * 1000
const FUTURE_VALIDATION_EXPIRY = new Date(Date.now() + ONE_YEAR_MS).toISOString()

const buildAnimal = (overrides = {}) => ({
  id: 'animal-1',
  name: 'Rex',
  species: 'DOG',
  breed: 'Labrador',
  birthDate: '2020-01-01',
  weight: 25,
  bloodGroup: 'DEA 1.1-',
  isVaccinated: true,
  isSterilized: true,
  donationFrequency: 'TWICE_YEAR',
  // Requis par checkEligibility (critère 1, isValidatedDonor) et critère 3
  // (satisfiesFrequencyRule) -- voir src/services/eligibility-service.js.
  isValidatedDonor: true,
  validationExpiresAt: FUTURE_VALIDATION_EXPIRY,
  lastDonationDate: null,
  ownerID: 'owner-1',
  createdAt: '2024-01-01T00:00:00.000Z',
  ...overrides,
})

const buildRequest = (overrides = {}) => ({
  id: 'request-1',
  requiredSpecies: 'DOG',
  requiredBloodGroup: 'DEA 1.1-',
  requestType: 'EMERGENCY',
  status: 'OPEN',
  createdAt: '2024-01-01T00:00:00.000Z',
  clinicID: 'clinic-1',
  clinic: {
    id: 'clinic-1',
    name: 'Clinique du Centre',
    latitude: CLINIC_LAT,
    longitude: CLINIC_LON,
  },
  activeMissionID: null,
  updatedAt: '2024-01-01T00:00:00.000Z',
  ...overrides,
})

/**
 * Configure les 5 mocks Gen2 vers les fixtures fournies, mirroring ce que
 * useOwnerProfile.fetchProfile / useAnimals.fetchAnimals / useOwnerAvailability.
 * fetchAvailabilities / useMatchingRequests.js appellent réellement.
 *
 * `clinicRelations` defaults to `[]` — most tests don't care about Clinic
 * Priority (critère 5) and must keep behaving exactly as before this was
 * wired in (regression coverage, see the dedicated `describe` block below).
 *
 * `availabilities` defaults to `[]` — Phase 6.5 (ADR-0005) : useMatchingRequests only
 * queries OwnerAvailability.list() when at least one open Request is APPOINTMENT (see the
 * dedicated `describe` block below), so most tests here never trigger it at all.
 */
function mockGraphqlResponses({ profile, animals, requests, clinicRelations = [], availabilities = [] }) {
  ownerGetMock.mockResolvedValue({ data: profile, errors: undefined })
  animalListMock.mockResolvedValue({ data: animals, errors: undefined })
  availabilityListMock.mockResolvedValue({ data: availabilities, errors: undefined })
  relationListMock.mockResolvedValue({ data: clinicRelations, errors: undefined })
  requestListMock.mockResolvedValue({ data: requests, errors: undefined })
}

describe('useMatchingRequests', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
    ownerGetMock.mockReset()
    animalListMock.mockReset()
    availabilityListMock.mockReset()
    relationListMock.mockReset()
    requestListMock.mockReset()
    // Réinitialise explicitement à chaque test la valeur par défaut ('owner-1',
    // celle utilisée par toutes les fixtures ci-dessus) : ce module mock n'a pas
    // `restoreMocks`/`clearMocks` activé dans vitest.config.js, et un test qui
    // reconfigure getCurrentUser() (voir describe Clinic Priority ci-dessous) ne
    // doit pas laisser fuiter cette valeur vers les tests suivants.
    vi.mocked(getCurrentUser).mockResolvedValue({ userId: 'owner-1' })
  })

  // Pin le `selectionSet` réellement envoyé par useMatchingRequests.js à
  // `client.models.Request.list()` (pas juste ce que les fixtures mockées injectent) : si la
  // relation `clinic` imbriquée (id/name/latitude/longitude) est un jour retirée de ce
  // selectionSet (régression du bug #3 documenté en tête de fichier), ce test échoue même si
  // les fixtures mockées ci-dessous continuent, elles, d'injecter `clinic` à la main.
  it("interroge Request.list() avec un selectionSet qui inclut bien la relation clinic imbriquée (id/name/latitude/longitude)", async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [buildAnimal()],
      requests: [buildRequest()],
    })

    const { searchMatches } = useMatchingRequests()
    await searchMatches()

    expect(requestListMock).toHaveBeenCalledWith(
      expect.objectContaining({
        selectionSet: expect.arrayContaining(['clinic.id', 'clinic.name', 'clinic.latitude', 'clinic.longitude']),
      }),
    )
  })

  it('trouve un Match réel de bout en bout (profil + animal compatible + clinique proche)', async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [buildAnimal()],
      requests: [buildRequest()],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    // La preuve que fetchProfile() a bien été appelé (bug #1 et #2) : getOwner
    // a été requêté.
    expect(ownerGetMock).toHaveBeenCalled()

    expect(matches.value).toHaveLength(1)
    expect(matches.value[0].id).toBe('request-1')
    // La preuve que la clinique imbriquée a bien été sélectionnée (bug #3) :
    // le filtre géographique a pu attacher une distance calculée.
    expect(matches.value[0].distanceKM).toBeTypeOf('number')
    expect(matches.value[0].distanceKM).toBeLessThan(50)
    expect(matches.value[0].matchingAnimal.id).toBe('animal-1')
  })

  it('exclut une Request hors du rayon maxTravelDistance', async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile({ maxTravelDistance: 50 }),
      animals: [buildAnimal()],
      requests: [
        buildRequest({
          id: 'request-far',
          clinic: { id: 'clinic-far', name: 'Clinique lointaine', latitude: 45.764, longitude: 4.8357 }, // Lyon, ~390km de Paris
        }),
      ],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(0)
  })

  it("exclut une Request dont l'espèce ou le groupe sanguin ne correspond à aucun animal du propriétaire", async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [buildAnimal({ species: 'CAT', bloodGroup: 'A' })],
      requests: [buildRequest({ requiredSpecies: 'DOG', requiredBloodGroup: 'DEA 1.1-' })],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(0)
  })

  it("s'arrête sans appeler Request.list() si le propriétaire n'a aucun animal", async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [],
      requests: [buildRequest()],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(0)
    expect(requestListMock).not.toHaveBeenCalled()
  })

  // Cette régression n'existait PAS avant ce fix : searchMatches() filtrait
  // uniquement sur la géo puis `.find(isBloodCompatible)`, sans jamais
  // consulter isValidatedDonor/validationExpiresAt (critère 1 de
  // l'Eligibility, CONTEXT.md). Un animal non-validé, ou dont la validation
  // a expiré, aurait donc été proposé comme match sur `main`, alors même que
  // son groupe sanguin et la distance étaient parfaitement compatibles. Ce
  // test aurait échoué sur `main` (matches.value aurait eu 1 élément).
  it("exclut une Request si l'unique animal compatible n'est pas (ou plus) un Validated Donor", async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [buildAnimal({ isValidatedDonor: false })],
      requests: [buildRequest()],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(0)
  })

  it('exclut une Request si la validation Donor de l\'unique animal compatible a expiré', async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [
        buildAnimal({
          isValidatedDonor: true,
          validationExpiresAt: '2020-01-01T00:00:00.000Z', // expirée depuis longtemps
        }),
      ],
      requests: [buildRequest()],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(0)
  })

  // Même constat que ci-dessus pour la Frequency Rule (critère 3) : l'ancienne
  // version de searchMatches() ne consultait ni lastDonationDate ni
  // donationFrequency. Un animal ayant donné il y a 5 jours avec une
  // TWICE_YEAR (minimum 182 jours, cf. MIN_DAYS_BETWEEN_DONATIONS) serait
  // ressorti comme match sur `main`. Ce test aurait échoué sur `main`.
  it("exclut une Request si l'unique animal compatible a donné trop récemment (Frequency Rule)", async () => {
    const fiveDaysAgo = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString()

    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [
        buildAnimal({
          donationFrequency: 'TWICE_YEAR',
          lastDonationDate: fiveDaysAgo,
        }),
      ],
      requests: [buildRequest()],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(0)
  })

  // La boucle de useMatchingRequests.searchMatches() est un `for...of` classique
  // (pas un `.find()`/`.some()` qui s'arrêterait sur le premier animal testé,
  // qu'il soit éligible ou non) : si le premier animal du propriétaire échoue
  // un critère de l'Eligibility, le deuxième doit quand même être évalué et,
  // s'il est éligible, faire matcher la Request. Un refactor qui réintroduirait
  // un `.find(animal => checkEligibility(...).eligible)` court-circuiterait
  // silencieusement sur le premier animal et exclurait à tort toute la Request
  // dès que le premier animal listé n'est pas le bon donneur.
  it("matche la Request avec le deuxième animal du propriétaire quand le premier échoue un critère d'Eligibility", async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile(),
      animals: [
        buildAnimal({ id: 'animal-not-donor', isValidatedDonor: false }),
        buildAnimal({ id: 'animal-eligible' }),
      ],
      requests: [buildRequest()],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value).toHaveLength(1)
    expect(matches.value[0].matchingAnimal.id).toBe('animal-eligible')
    // distanceKM doit provenir du checkEligibility() de l'animal réellement
    // éligible (animal-eligible), pas rester `null`/`undefined` comme le
    // renvoie checkEligibility() pour l'animal non-donneur testé en premier
    // (NOT_VALIDATED_DONOR court-circuite avant le calcul de distance, cf.
    // eligibility-service.js) -- preuve qu'aucune valeur périmée d'un animal
    // précédemment testé ne "fuit" sur le résultat final.
    expect(matches.value[0].distanceKM).toBeTypeOf('number')
    expect(matches.value[0].distanceKM).toBeGreaterThan(0)
    expect(matches.value[0].distanceKM).toBeLessThan(50)
  })

  it('trie les Matches par distance croissante', async () => {
    mockGraphqlResponses({
      profile: buildOwnerProfile({ maxTravelDistance: 500 }),
      animals: [buildAnimal()],
      requests: [
        buildRequest({
          id: 'request-far',
          clinic: { id: 'clinic-b', name: 'B', latitude: 45.764, longitude: 4.8357 }, // Lyon
        }),
        buildRequest({
          id: 'request-near',
          clinic: { id: 'clinic-a', name: 'A', latitude: CLINIC_LAT, longitude: CLINIC_LON }, // Paris, proche
        }),
      ],
    })

    const { matches, searchMatches } = useMatchingRequests()

    await searchMatches()

    expect(matches.value.map((m) => m.id)).toEqual(['request-near', 'request-far'])
  })

  // Critère 5 de l'Eligibility (Clinic Priority, CONTEXT.md) : jusqu'à ce fix,
  // searchMatches() appelait toujours checkEligibility() avec ownerClinicIds
  // resté à sa valeur par défaut ([]) -> hasClinicPriority était toujours
  // false et ce critère n'affectait jamais rien de visible pour l'Owner.
  describe('Clinic Priority (critère 5)', () => {
    it("interroge ClinicOwnerRelation.list() avec l'ownerID de getCurrentUser(), pas une valeur en dur", async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile(),
        animals: [buildAnimal()],
        requests: [buildRequest()],
        clinicRelations: [],
      })

      const { searchMatches } = useMatchingRequests()

      await searchMatches()

      expect(relationListMock).toHaveBeenCalledWith(
        expect.objectContaining({ filter: { ownerID: { eq: 'owner-1' } } }),
      )
    })

    // Renforce le test précédent : toutes les fixtures de ce fichier utilisent
    // 'owner-1' aussi bien comme userId (mock getCurrentUser) que comme id de
    // profil (buildOwnerProfile), donc un code qui écrirait `ownerID: 'owner-1'`
    // en dur au lieu de lire `userId` depuis getCurrentUser() passerait quand
    // même le test ci-dessus par coïncidence. Ici, getCurrentUser() renvoie
    // délibérément un userId QUI NE CORRESPOND À AUCUNE fixture ('owner-42') :
    // seule une vraie lecture de getCurrentUser().userId peut faire matcher
    // cette assertion.
    it("propage le userId réel de getCurrentUser(), pas la valeur 'owner-1' qui apparaît par ailleurs dans les fixtures", async () => {
      vi.mocked(getCurrentUser).mockResolvedValue({ userId: 'owner-42' })

      mockGraphqlResponses({
        profile: buildOwnerProfile(),
        animals: [buildAnimal()],
        requests: [buildRequest()],
        clinicRelations: [],
      })

      const { searchMatches } = useMatchingRequests()

      await searchMatches()

      expect(relationListMock).toHaveBeenCalledWith(
        expect.objectContaining({ filter: { ownerID: { eq: 'owner-42' } } }),
      )
    })

    // Relevé en Lead Dev review : Clinic Priority est un critère explicitement
    // non-exclusif ("favorise, sans exclure", CONTEXT.md). Un échec transitoire de CET
    // appel précis (throttling, hoquet @auth...) ne doit dégrader QUE le tri (repli sur
    // "aucune priorité connue"), jamais vider matches.value en entier — sinon un critère
    // purement consultatif finirait par exclure accidentellement TOUTES les Requests.
    it("un échec de ClinicOwnerRelation.list() ne vide pas matches.value — dégrade juste Clinic Priority à false pour tout le monde", async () => {
      const requestNear = buildRequest({ id: 'request-near', clinic: { latitude: 48.8567, longitude: 2.3522 } })

      ownerGetMock.mockResolvedValue({ data: buildOwnerProfile(), errors: undefined })
      animalListMock.mockResolvedValue({ data: [buildAnimal()], errors: undefined })
      relationListMock.mockRejectedValue(new Error('réseau : timeout'))
      requestListMock.mockResolvedValue({ data: [requestNear], errors: undefined })

      const consoleErrorSpy = vi.spyOn(console, 'error').mockImplementation(() => {})

      const { searchMatches, matches } = useMatchingRequests()
      await searchMatches()

      expect(matches.value).toHaveLength(1)
      expect(matches.value[0].id).toBe('request-near')
      expect(matches.value[0].hasClinicPriority).toBe(false)
      expect(consoleErrorSpy).toHaveBeenCalled()

      consoleErrorSpy.mockRestore()
    })

    // Décision produit actée avec le repo owner (voir le commentaire au-dessus du
    // comparateur dans useMatchingRequests.searchMatches) : le groupement inconditionnel
    // qu'on testait ici auparavant (une Request de Clinic Priority arbitrairement lointaine
    // devant une Request très proche d'une clinique inconnue) est explicitement rejeté pour
    // une app d'urgence sanguine. Ce test vérifie maintenant l'ABSENCE de ce comportement :
    // une Request liée à une Clinic déjà connue mais hors du rayon de boost
    // (CLINIC_PRIORITY_BOOST_RADIUS_KM = 15km) ne doit PAS passer devant une Request bien
    // plus proche, même sans relation existante -- le tri retombe sur la distance pure.
    it("ne fait PAS remonter en tête une Request liée à une Clinic connue si elle dépasse le rayon de boost, même si l'autre Request compatible n'a pas de relation existante", async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile({ maxTravelDistance: 500 }),
        animals: [buildAnimal()],
        requests: [
          buildRequest({
            id: 'request-near-unknown-clinic',
            clinic: { id: 'clinic-unknown', name: 'Inconnue', latitude: CLINIC_LAT, longitude: CLINIC_LON }, // Paris, très proche (~2km)
          }),
          buildRequest({
            id: 'request-far-known-clinic',
            clinic: { id: 'clinic-known', name: 'Connue', latitude: 45.764, longitude: 4.8357 }, // Lyon, ~390km -- très au-delà du rayon de boost
          }),
        ],
        clinicRelations: [{ clinicID: 'clinic-known' }],
      })

      const { matches, searchMatches } = useMatchingRequests()

      await searchMatches()

      // Tri par distance pure : la Request lointaine (même Clinic Priority) ne passe pas
      // devant la Request proche.
      expect(matches.value.map((m) => m.id)).toEqual([
        'request-near-unknown-clinic',
        'request-far-known-clinic',
      ])
      // `hasClinicPriority` (le booléen brut affiché en badge dans DashboardView.vue) reste
      // inchangé par le plafond de distance : seul le comparateur de tri est affecté.
      expect(matches.value.find((m) => m.id === 'request-far-known-clinic').hasClinicPriority).toBe(true)
      expect(matches.value.find((m) => m.id === 'request-near-unknown-clinic').hasClinicPriority).toBe(false)
    })

    // Cas réaliste avec PLUSIEURS Requests de chaque côté (2 avec Clinic Priority, 2 sans),
    // à distances volontairement entremêlées -- pas seulement 2 Requests comme le test
    // ci-dessus. C'est le cas le plus susceptible de démasquer un comparateur bugué qui ne
    // gérerait correctement qu'une comparaison à 2 éléments (ex. un simple `if (a.has) return
    // -1` sans gérer le groupe symétrique, ou un comparateur non transitif) mais casserait
    // sous le tri multi-éléments réel d'Array.prototype.sort.
    //
    // Avec le plafond de distance (CLINIC_PRIORITY_BOOST_RADIUS_KM = 15km), seule
    // 'request-priority-close' (~2km, sous le plafond) est réellement boostée. 'request-
    // priority-far' (~390km, Clinic Priority mais largement hors plafond) n'est PAS boostée
    // et retombe dans le tri par distance pure avec les Requests non-priority -- où elle finit
    // après 'request-nonpriority-veryclose' (~0km) mais avant 'request-nonpriority-farthest'
    // (~660km). `hasClinicPriority` (badge brut) reste `true` sur ces deux Requests malgré
    // tout : seul l'ORDRE change, jamais l'indicateur affiché.
    it('avec plusieurs Requests des deux côtés, seules les Requests Clinic Priority sous le rayon de boost sortent en tête ; au-delà, le tri redevient une pure distance croissante', async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile({ maxTravelDistance: 1000 }),
        animals: [buildAnimal()],
        requests: [
          // Volontairement pas déjà triées par distance dans le tableau d'entrée : le tri
          // doit reposer sur le comparateur, pas sur un ordre d'entrée qui masquerait un bug.
          buildRequest({
            id: 'request-nonpriority-farthest',
            clinic: { id: 'clinic-marseille', name: 'Marseille', latitude: 43.2965, longitude: 5.3698 }, // ~660km
          }),
          buildRequest({
            id: 'request-priority-close',
            clinic: { id: 'clinic-known-close', name: 'Paris (connue)', latitude: CLINIC_LAT, longitude: CLINIC_LON }, // ~2km, sous le plafond
          }),
          buildRequest({
            id: 'request-nonpriority-veryclose',
            clinic: { id: 'clinic-unknown-veryclose', name: 'Inconnue (très proche)', latitude: OWNER_LAT, longitude: OWNER_LON }, // ~0km
          }),
          buildRequest({
            id: 'request-priority-far',
            clinic: { id: 'clinic-known-far', name: 'Lyon (connue)', latitude: 45.764, longitude: 4.8357 }, // ~390km, Clinic Priority mais hors plafond
          }),
        ],
        clinicRelations: [{ clinicID: 'clinic-known-close' }, { clinicID: 'clinic-known-far' }],
      })

      const { matches, searchMatches } = useMatchingRequests()

      await searchMatches()

      // Seule 'request-priority-close' (boostée) sort en tête. Le reste est trié par
      // distance pure, sans notion de groupe : 'request-priority-far' (~390km) ne repasse
      // pas devant 'request-nonpriority-veryclose' (~0km) malgré son statut Clinic Priority.
      expect(matches.value.map((m) => m.id)).toEqual([
        'request-priority-close',
        'request-nonpriority-veryclose',
        'request-priority-far',
        'request-nonpriority-farthest',
      ])
      // `hasClinicPriority` (badge brut, indépendant de la distance) reste correct pour
      // chaque Request malgré leur ordre entremêlé.
      expect(matches.value.find((m) => m.id === 'request-priority-close').hasClinicPriority).toBe(true)
      expect(matches.value.find((m) => m.id === 'request-priority-far').hasClinicPriority).toBe(true)
      expect(matches.value.find((m) => m.id === 'request-nonpriority-veryclose').hasClinicPriority).toBe(false)
      expect(matches.value.find((m) => m.id === 'request-nonpriority-farthest').hasClinicPriority).toBe(false)
    })

    // Limite exacte du plafond (CLINIC_PRIORITY_BOOST_RADIUS_KM = 15km) : une Request Clinic
    // Priority à distance <= 15km doit être boostée (comparaison inclusive, `<=` dans le
    // comparateur), une à distance > 15km ne doit pas l'être. Une Request non-priority à 10km
    // sert de témoin : plus proche que les deux Requests priority, mais pas boostée -- si le
    // plafond avait une erreur d'inégalité stricte/large ou une confusion de signe, ce témoin
    // la révélerait en se retrouvant du mauvais côté du tri.
    it('applique le plafond de distance de façon inclusive à la limite exacte (15km boostée, 15.1km non boostée)', async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile({ maxTravelDistance: 1000 }),
        animals: [buildAnimal()],
        requests: [
          buildRequest({
            id: 'request-priority-above-limit',
            // ~15.1km de l'Owner (arrondi) -- juste au-dessus du plafond, Clinic Priority mais
            // pas boostée.
            clinic: { id: 'clinic-above-limit', name: 'Au-delà du plafond', latitude: 49.005645, longitude: OWNER_LON },
          }),
          buildRequest({
            id: 'request-nonpriority-control',
            // ~10km de l'Owner, sans Clinic Priority : plus proche que les deux Requests
            // priority ci-dessus/dessous, mais jamais boostée -- sert de témoin.
            clinic: { id: 'clinic-control', name: 'Témoin, sans relation', latitude: 48.959831, longitude: OWNER_LON },
          }),
          buildRequest({
            id: 'request-priority-at-limit',
            // ~15.0km de l'Owner (arrondi) -- exactement au plafond, doit être boostée
            // (comparaison `<=`, pas `<`).
            clinic: { id: 'clinic-at-limit', name: 'Exactement au plafond', latitude: 49.004747, longitude: OWNER_LON },
          }),
        ],
        clinicRelations: [{ clinicID: 'clinic-above-limit' }, { clinicID: 'clinic-at-limit' }],
      })

      const { matches, searchMatches } = useMatchingRequests()

      await searchMatches()

      expect(matches.value.map((m) => m.distanceKM)).toEqual([15, 10, 15.1])
      expect(matches.value.map((m) => m.id)).toEqual([
        'request-priority-at-limit',
        'request-nonpriority-control',
        'request-priority-above-limit',
      ])
    })

    // Régression : sans aucune ClinicOwnerRelation existante pour cet Owner (cas normal
    // pour un nouvel Owner), le tri doit rester purement par distance -- comme avant ce
    // fix, et comme le garantit déjà 'trie les Matches par distance croissante' ci-dessus
    // (clinicRelations: [] par défaut). Ce test le rend explicite pour Clinic Priority.
    it('sans aucune ClinicOwnerRelation, trie toujours par distance seule', async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile({ maxTravelDistance: 500 }),
        animals: [buildAnimal()],
        requests: [
          buildRequest({
            id: 'request-far',
            clinic: { id: 'clinic-b', name: 'B', latitude: 45.764, longitude: 4.8357 }, // Lyon
          }),
          buildRequest({
            id: 'request-near',
            clinic: { id: 'clinic-a', name: 'A', latitude: CLINIC_LAT, longitude: CLINIC_LON }, // Paris, proche
          }),
        ],
        clinicRelations: [],
      })

      const { matches, searchMatches } = useMatchingRequests()

      await searchMatches()

      expect(matches.value.map((m) => m.id)).toEqual(['request-near', 'request-far'])
      expect(matches.value.every((m) => m.hasClinicPriority === false)).toBe(true)
    })
  })

  // Phase 7.6 (R-09) : loadError distingue "recherche en échec" d'une absence réelle
  // d'urgence à proximité -- DashboardView.vue (radar d'urgence Owner, roadmap Phase 6.2)
  // affichait auparavant le même message rassurant dans les deux cas.
  describe('loadError (Phase 7.6, R-09)', () => {
    it("un échec explicite (searchMatches() par défaut) du flux principal met loadError à true", async () => {
      ownerGetMock.mockResolvedValue({ data: buildOwnerProfile(), errors: undefined })
      animalListMock.mockResolvedValue({ data: [buildAnimal()], errors: undefined })
      relationListMock.mockResolvedValue({ data: [], errors: undefined })
      requestListMock.mockRejectedValue(new Error('réseau : timeout'))
      const consoleErrorSpy = vi.spyOn(console, 'error').mockImplementation(() => {})

      const { searchMatches, loadError, matches } = useMatchingRequests()
      expect(loadError.value).toBe(false)

      await searchMatches()

      expect(loadError.value).toBe(true)
      expect(matches.value).toEqual([])

      consoleErrorSpy.mockRestore()
    })

    it("un échec silencieux (searchMatches({ silent: true }), polling/retour de focus) ne met JAMAIS loadError à true", async () => {
      ownerGetMock.mockResolvedValue({ data: buildOwnerProfile(), errors: undefined })
      animalListMock.mockResolvedValue({ data: [buildAnimal()], errors: undefined })
      relationListMock.mockResolvedValue({ data: [], errors: undefined })
      requestListMock.mockRejectedValue(new Error('réseau : timeout'))
      const consoleErrorSpy = vi.spyOn(console, 'error').mockImplementation(() => {})

      const { searchMatches, loadError } = useMatchingRequests()

      await searchMatches({ silent: true })

      expect(loadError.value).toBe(false)

      consoleErrorSpy.mockRestore()
    })

    it('un rafraîchissement réussi (silencieux ou non) efface un loadError laissé par un appel explicite précédent', async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile(),
        animals: [buildAnimal()],
        requests: [buildRequest()],
      })

      const { searchMatches, loadError } = useMatchingRequests()

      // 1er appel explicite : échec du flux principal -- déclenché sur `Owner.get`
      // (fetchProfile(), le tout premier appel réseau de searchMatches()) plutôt que sur
      // `requestListMock` : une lecture secondaire (ClinicOwnerRelation.list, voir le test
      // dédié plus bas) ne doit PAS mettre loadError à true -- donc cibler ownerGetMock ici
      // est la seule façon de continuer à représenter un vrai échec du flux PRINCIPAL, pas
      // de la lecture secondaire.
      ownerGetMock.mockRejectedValueOnce(new Error('réseau : timeout'))
      const consoleErrorSpy = vi.spyOn(console, 'error').mockImplementation(() => {})
      await searchMatches()
      expect(loadError.value).toBe(true)

      // 2e appel, silencieux cette fois, qui réussit : doit effacer l'erreur précédente.
      await searchMatches({ silent: true })
      expect(loadError.value).toBe(false)

      consoleErrorSpy.mockRestore()
    })

    it("un échec de la lecture secondaire Clinic Priority (ClinicOwnerRelation.list) ne met PAS loadError à true -- reste une dégradation isolée du tri", async () => {
      const requestNear = buildRequest({ id: 'request-near', clinic: { latitude: 48.8567, longitude: 2.3522 } })

      ownerGetMock.mockResolvedValue({ data: buildOwnerProfile(), errors: undefined })
      animalListMock.mockResolvedValue({ data: [buildAnimal()], errors: undefined })
      relationListMock.mockRejectedValue(new Error('réseau : timeout'))
      requestListMock.mockResolvedValue({ data: [requestNear], errors: undefined })
      const consoleErrorSpy = vi.spyOn(console, 'error').mockImplementation(() => {})

      const { searchMatches, matches, loadError } = useMatchingRequests()
      await searchMatches()

      expect(matches.value).toHaveLength(1)
      expect(loadError.value).toBe(false)

      consoleErrorSpy.mockRestore()
    })
  })

  // Phase 6.5 (ADR-0005) : filtre EXCLUSIF supplémentaire pour les Requests APPOINTMENT,
  // câblé dans useMatchingRequests.js en plus de checkEligibility() (jamais à sa place --
  // matchesAvailability() elle-même est testée en isolation dans
  // src/services/__tests__/eligibility-service.availability.test.js). Ces tests couvrent
  // uniquement le CÂBLAGE : le déclenchement conditionnel de OwnerAvailability.list(), et le
  // fait qu'un résultat "non disponible" exclut bien la Request du match final.
  describe('APPOINTMENT / OwnerAvailability (Phase 6.5, ADR-0005)', () => {
    // Mercredi 12 août 2026, 10h30 (heure locale) -- Date.prototype.getDay() === 3, même
    // fixture que eligibility-service.availability.test.js.
    const WEDNESDAY_10_30 = new Date(2026, 7, 12, 10, 30, 0).toISOString()

    const buildAppointmentRequest = (overrides = {}) =>
      buildRequest({
        id: 'request-appointment',
        requestType: 'APPOINTMENT',
        appointmentDatetime: WEDNESDAY_10_30,
        ...overrides,
      })

    it("n'interroge PAS OwnerAvailability.list() si aucune Request ouverte n'est APPOINTMENT (coût GraphQL évité pour le cas le plus fréquent)", async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile(),
        animals: [buildAnimal()],
        requests: [buildRequest()], // EMERGENCY par défaut
      })

      const { searchMatches } = useMatchingRequests()
      await searchMatches()

      expect(availabilityListMock).not.toHaveBeenCalled()
    })

    it('interroge OwnerAvailability.list() dès qu\'au moins une Request ouverte est APPOINTMENT', async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile(),
        animals: [buildAnimal()],
        requests: [buildAppointmentRequest()],
        availabilities: [{ dayOfWeek: 3, startTime: '09:00', endTime: '12:00' }],
      })

      const { searchMatches } = useMatchingRequests()
      await searchMatches()

      expect(availabilityListMock).toHaveBeenCalled()
    })

    it('inclut une Request APPOINTMENT dont appointmentDatetime tombe dans une OwnerAvailability', async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile(),
        animals: [buildAnimal()],
        requests: [buildAppointmentRequest()],
        availabilities: [{ dayOfWeek: 3, startTime: '09:00', endTime: '12:00' }],
      })

      const { matches, searchMatches } = useMatchingRequests()
      await searchMatches()

      expect(matches.value).toHaveLength(1)
      expect(matches.value[0].id).toBe('request-appointment')
    })

    it("exclut une Request APPOINTMENT par ailleurs éligible (checkEligibility OK) si aucune OwnerAvailability ne couvre le jour/l'heure demandés", async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile(),
        animals: [buildAnimal()],
        requests: [buildAppointmentRequest()],
        // Créneau un jeudi -- ne couvre jamais un rendez-vous un mercredi.
        availabilities: [{ dayOfWeek: 4, startTime: '09:00', endTime: '12:00' }],
      })

      const { matches, searchMatches } = useMatchingRequests()
      await searchMatches()

      expect(matches.value).toHaveLength(0)
    })

    it("inclut une Request APPOINTMENT si l'Owner n'a renseigné AUCUNE OwnerAvailability (\"toujours disponible\" par défaut, amendement ADR-0005 2026-08-17)", async () => {
      const appointmentReq = buildAppointmentRequest()
      mockGraphqlResponses({
        profile: buildOwnerProfile(),
        animals: [buildAnimal()],
        requests: [appointmentReq],
        availabilities: [],
      })

      const { matches, searchMatches } = useMatchingRequests()
      await searchMatches()

      expect(matches.value.map((m) => m.id)).toEqual([appointmentReq.id])
    })

    it("inclut une Request APPOINTMENT (\"toujours disponible\" par défaut) si OwnerAvailability.list() échoue en réseau, sans faire planter searchMatches() ni vider le reste de matches.value", async () => {
      const appointmentReq = buildAppointmentRequest()
      const emergencyReq = buildRequest({ id: 'request-emergency' })

      ownerGetMock.mockResolvedValue({ data: buildOwnerProfile(), errors: undefined })
      animalListMock.mockResolvedValue({ data: [buildAnimal()], errors: undefined })
      availabilityListMock.mockRejectedValue(new Error('réseau : timeout'))
      relationListMock.mockResolvedValue({ data: [], errors: undefined })
      requestListMock.mockResolvedValue({ data: [appointmentReq, emergencyReq], errors: undefined })

      const consoleErrorSpy = vi.spyOn(console, 'error').mockImplementation(() => {})

      const { matches, searchMatches } = useMatchingRequests()
      await searchMatches()

      // La Request EMERGENCY n'est jamais concernée par matchesAvailability() -- son match
      // survit intact à l'échec de OwnerAvailability.list(). La Request APPOINTMENT survit elle
      // aussi désormais : ownerAvailabilities.value retombe sur [] (défaut de
      // useOwnerAvailability.js après l'échec réseau), et matchesAvailability(..., [])
      // renvoie `true` depuis l'amendement ADR-0005 (2026-08-17).
      expect(matches.value.map((m) => m.id).sort()).toEqual(
        [appointmentReq.id, 'request-emergency'].sort(),
      )
      expect(consoleErrorSpy).toHaveBeenCalled()

      consoleErrorSpy.mockRestore()
    })

    it('ignore matchesAvailability pour une Request EMERGENCY même sans aucune OwnerAvailability compatible', async () => {
      mockGraphqlResponses({
        profile: buildOwnerProfile(),
        animals: [buildAnimal()],
        // EMERGENCY par défaut + une APPOINTMENT non disponible, pour prouver que le filtre
        // ne s'applique bien qu'à la seconde.
        requests: [buildRequest({ id: 'request-emergency' }), buildAppointmentRequest()],
        availabilities: [{ dayOfWeek: 4, startTime: '09:00', endTime: '12:00' }], // jeudi seulement
      })

      const { matches, searchMatches } = useMatchingRequests()
      await searchMatches()

      expect(matches.value.map((m) => m.id)).toEqual(['request-emergency'])
    })
  })

  // Phase 4.1 (roadmap V1) : fallback dashboard au vrai push PWA (hors périmètre V1).
  // Ces tests couvrent uniquement le mécanisme de déclenchement (polling + retour de
  // focus + nettoyage), pas le contenu du matching déjà couvert ci-dessus -- les
  // fixtures ici restent volontairement minimales (aucun animal) pour que
  // searchMatches() s'arrête tôt (guard "pas d'animaux") tout en émettant quand même
  // les appels GraphQL qui suffisent à prouver qu'un nouveau cycle de recherche a bien
  // été déclenché.
  //
  // Phase 8, sous-tâche 5 (lot 1/3, correction post-lot) : la preuve "un cycle a tourné"
  // ci-dessous cible désormais `animalListMock` (Animal.list, useAnimals.fetchAnimals())
  // plutôt que `graphqlMock` -- deux raisons combinées. (1) GetOwner ne transite plus par
  // `graphqlMock` depuis la migration Gen2 de useOwnerProfile.js (voir `mockGraphqlResponses`
  // plus haut). (2) `Owner.get` n'aurait de toute façon pas été un signal fiable pour un
  // polling répété : `useOwnerProfile.fetchProfile()` a un cache par session (`isLoaded`,
  // R-19) qui rend les appels suivants no-op sur la MÊME instance de composable -- il ne se
  // déclenche donc qu'au tout premier tick, jamais aux suivants. `fetchAnimals()` n'a lui
  // aucun cache et est rappelé à chaque searchMatches() tant que `animals.value` reste vide
  // (le cas ici, fixtures `animals: []`) : c'est le signal qui grossit de façon fiable à
  // chaque tick, exactement ce que ces tests vérifient.
  //
  // 60_000 ci-dessous doit rester synchronisé avec DASHBOARD_REFRESH_INTERVAL_MS
  // (useMatchingRequests.js) -- ce n'est pas exporté (détail d'implémentation), donc
  // ces tests le dupliquent en dur comme le reste de ce fichier pin déjà des
  // constantes non exportées ailleurs (CLINIC_PRIORITY_BOOST_RADIUS_KM = 15 plus haut).
  describe('startAutoRefresh / stopAutoRefresh (Phase 4.1, rafraîchissement dashboard)', () => {
    const REFRESH_INTERVAL_MS = 60_000

    const setVisibility = (state) => {
      Object.defineProperty(document, 'visibilityState', {
        configurable: true,
        get: () => state,
      })
    }

    // Chaque appel à useMatchingRequests() dans ce describe passe par ce wrapper plutôt
    // que l'import direct, pour que l'afterEach ci-dessous puisse systématiquement
    // appeler stopAutoRefresh() sur CHAQUE instance créée -- y compris celles des tests
    // qui n'appellent pas eux-mêmes stopAutoRefresh() (ex. le test "retour de focus").
    // Sans ça, un `document.addEventListener('visibilitychange', ...)` laissé actif par
    // un test fuite silencieusement vers les tests suivants (même `document` jsdom
    // partagé), qui verraient alors des appels GraphQL inattendus déclenchés par un
    // listener d'un test précédent -- constaté en écrivant ces tests.
    const instances = []
    const createMatchingRequests = () => {
      const instance = useMatchingRequests()
      instances.push(instance)
      return instance
    }

    beforeEach(() => {
      mockGraphqlResponses({ profile: buildOwnerProfile(), animals: [], requests: [] })
      setVisibility('visible')
      instances.length = 0
    })

    afterEach(() => {
      instances.forEach((instance) => instance.stopAutoRefresh())
      vi.useRealTimers()
      // `visibilityState` est un getter sur `Document.prototype` en jsdom, pas une
      // propriété propre à l'instance `document` : `getOwnPropertyDescriptor(document,
      // ...)` renvoie toujours `undefined`, donc un `if (original) { restore }` ne
      // s'exécute jamais et la propriété propre posée par `setVisibility()` fuite
      // silencieusement sur le `document` jsdom partagé vers les describe suivants de ce
      // fichier (constaté en Lead Dev review). `delete` retire la propriété propre
      // inconditionnellement et fait retomber l'accès sur le getter du prototype.
      delete document.visibilityState
    })

    it("relance searchMatches() à chaque tick de l'interval tant que l'onglet est visible", async () => {
      vi.useFakeTimers()

      const { startAutoRefresh } = createMatchingRequests()
      startAutoRefresh()

      // Rien avant le premier tick.
      expect(animalListMock).not.toHaveBeenCalled()

      await vi.advanceTimersByTimeAsync(REFRESH_INTERVAL_MS)
      const callsAfterFirstTick = animalListMock.mock.calls.length
      expect(callsAfterFirstTick).toBeGreaterThan(0)

      await vi.advanceTimersByTimeAsync(REFRESH_INTERVAL_MS)
      expect(animalListMock.mock.calls.length).toBeGreaterThan(callsAfterFirstTick)
    })

    it("ne relance PAS searchMatches() au tick de l'interval si l'onglet est en arrière-plan (visibilityState !== 'visible')", async () => {
      vi.useFakeTimers()
      setVisibility('hidden')

      const { startAutoRefresh } = createMatchingRequests()
      startAutoRefresh()

      await vi.advanceTimersByTimeAsync(REFRESH_INTERVAL_MS)

      expect(animalListMock).not.toHaveBeenCalled()
    })

    it("déclenche un refresh immédiat sur un retour de focus (`visibilitychange`), sans attendre le prochain tick de l'interval", async () => {
      const { startAutoRefresh } = createMatchingRequests()
      startAutoRefresh()

      // Ici, `ownerGetMock` (pas `animalListMock`) : ce test ne flush que 2 microtasks après
      // l'évènement, insuffisant pour atteindre le `fetchAnimals()` qui suit `fetchProfile()`
      // dans searchMatches() -- `Owner.get()` (fetchProfile(), le tout premier appel réseau)
      // reste le signal le plus rapide à observer pour "un nouveau cycle a démarré", sans
      // dépendre du nombre de microtasks jusqu'au second appel.
      expect(ownerGetMock).not.toHaveBeenCalled()

      document.dispatchEvent(new Event('visibilitychange'))
      await Promise.resolve()
      await Promise.resolve()

      expect(ownerGetMock).toHaveBeenCalled()
    })

    it("stopAutoRefresh() arrête le polling : plus aucun appel après le tick suivant", async () => {
      vi.useFakeTimers()

      const { startAutoRefresh, stopAutoRefresh } = createMatchingRequests()
      startAutoRefresh()
      stopAutoRefresh()

      await vi.advanceTimersByTimeAsync(REFRESH_INTERVAL_MS * 2)

      expect(animalListMock).not.toHaveBeenCalled()
    })

    it("stopAutoRefresh() retire aussi le listener `visibilitychange` : un retour de focus après stop ne déclenche plus rien", async () => {
      const { startAutoRefresh, stopAutoRefresh } = createMatchingRequests()
      startAutoRefresh()
      stopAutoRefresh()

      document.dispatchEvent(new Event('visibilitychange'))
      await Promise.resolve()
      await Promise.resolve()

      expect(animalListMock).not.toHaveBeenCalled()
    })

    it('startAutoRefresh() est idempotent : un second appel remplace le premier interval au lieu de le doubler', async () => {
      vi.useFakeTimers()

      const { startAutoRefresh, stopAutoRefresh } = createMatchingRequests()
      startAutoRefresh()
      startAutoRefresh()
      // Un seul stopAutoRefresh() doit suffire à tout arrêter. Si le 2e startAutoRefresh()
      // avait laissé le 1er interval fuiter (pas d'appel à stopAutoRefresh() en tête de
      // startAutoRefresh()), celui-ci continuerait de tourner après ce stop et le test
      // échouerait sur l'assertion ci-dessous.
      stopAutoRefresh()

      await vi.advanceTimersByTimeAsync(REFRESH_INTERVAL_MS * 2)

      expect(animalListMock).not.toHaveBeenCalled()
    })
  })
})
