/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AddressAutocomplete: typeof import('./src/components/common/AddressAutocomplete.vue')['default']
    AdvancedNotificationSettings: typeof import('./src/components/notifications/AdvancedNotificationSettings.vue')['default']
    AppDatePicker: typeof import('./src/components/common/AppDatePicker.vue')['default']
    AppFooter: typeof import('./src/components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    AppMobileMenu: typeof import('./src/components/common/AppMobileMenu.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    CreateEmergencyForm: typeof import('./src/components/emergency/CreateEmergencyForm.vue')['default']
    DashboardSidebar: typeof import('./src/components/dashboard/DashboardSidebar.vue')['default']
    DataMigrationHelper: typeof import('./src/components/debug/DataMigrationHelper.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EmergencyCard: typeof import('./src/components/emergency/EmergencyCard.vue')['default']
    EmergencyDashboard: typeof import('./src/components/emergency/EmergencyDashboard.vue')['default']
    EmergencyDetails: typeof import('./src/components/emergency/EmergencyDetails.vue')['default']
    EmergencyNotification: typeof import('./src/components/notifications/EmergencyNotification.vue')['default']
    EmergencySettings: typeof import('./src/components/emergency/EmergencySettings.vue')['default']
    InfiniteScroll: typeof import('./src/components/common/InfiniteScroll.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MatchCard: typeof import('./src/components/matching/MatchCard.vue')['default']
    MatchCardSkeleton: typeof import('./src/components/matching/MatchCardSkeleton.vue')['default']
    MatchMap: typeof import('./src/components/matching/MatchMap.vue')['default']
    MatchResults: typeof import('./src/components/matching/MatchResults.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MissionCard: typeof import('./src/components/dashboard/MissionCard.vue')['default']
    MissionCardSkeleton: typeof import('./src/components/dashboard/MissionCardSkeleton.vue')['default']
    MissionDetails: typeof import('./src/components/tracking/MissionDetails.vue')['default']
    MissionsList: typeof import('./src/components/dashboard/MissionsList.vue')['default']
    MissionTracker: typeof import('./src/components/tracking/MissionTracker.vue')['default']
    MLInsights: typeof import('./src/components/analytics/MLInsights.vue')['default']
    NotificationBadge: typeof import('./src/components/notifications/NotificationBadge.vue')['default']
    NotificationCenter: typeof import('./src/components/notifications/NotificationCenter.vue')['default']
    NotificationItem: typeof import('./src/components/notifications/NotificationItem.vue')['default']
    NotificationMonitoring: typeof import('./src/components/admin/NotificationMonitoring.vue')['default']
    NotificationSettings: typeof import('./src/components/notifications/NotificationSettings.vue')['default']
    Password: typeof import('primevue/password')['default']
    PerformanceDashboard: typeof import('./src/components/admin/PerformanceDashboard.vue')['default']
    PhoneInput: typeof import('./src/components/common/PhoneInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreBar: typeof import('./src/components/matching/ScoreBar.vue')['default']
    Select: typeof import('primevue/select')['default']
    Slider: typeof import('primevue/slider')['default']
    SuccessProbability: typeof import('./src/components/matching/SuccessProbability.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
