#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Ce wizard n'écrit jamais dans le .env réel du projet (déjà utilisé pour
# d'autres secrets) — seulement dans ce fichier dédié, local et non commité.
ENV_FILE=".amplify-hosting-wizard.env"

TOTAL_STAGES=7

banner "Redlink — Phase 6.9 : hébergement Amplify Console (pilote)"

# ── Stage 1 ─────────────────────────────────────────────────────────────
stage "Console Amplify — nouvelle app hébergée"
say "Backend existant : app 'redlinkpwa', environnement 'dev', région eu-west-3."
say "On va créer une app HÉBERGÉE distincte pour le frontend, liée à ce backend —"
say "pas un nouveau backend."
open_url "https://eu-west-3.console.aws.amazon.com/amplify/home?region=eu-west-3#/create"
step "Vérifie en haut à droite que tu es bien dans la région eu-west-3 (Paris)."
step "Clique 'Host web app' (ou 'New app' → 'Host web app' selon la version de la console)."
pause "Fait ? Appuie sur Entrée pour continuer."

# ── Stage 2 ─────────────────────────────────────────────────────────────
stage "Connexion à GitHub (autorisation OAuth)"
say "Amplify a besoin d'un accès en lecture à ton repo GitHub pour le CI/CD."
step "Choisis 'GitHub' comme source."
step "Si demandé, autorise l'app GitHub 'AWS Amplify' (fenêtre GitHub qui s'ouvre) —"
step "  donne-lui accès au repo RedLink-Medical-Connect/redlink-pwa (pas 'All repositories'"
step "  si tu préfères limiter l'accès, uniquement ce repo suffit)."
step "Sélectionne le repo 'RedLink-Medical-Connect/redlink-pwa'."
step "Sélectionne la branche 'main'."
pause "Repo et branche sélectionnés ? Appuie sur Entrée pour continuer."

# ── Stage 3 ─────────────────────────────────────────────────────────────
stage "Liaison au backend Amplify EXISTANT (ne pas en créer un nouveau)"
warn "Étape la plus facile à rater : Amplify va détecter le dossier amplify/ du repo"
warn "et proposer de choisir un environnement backend. Il NE FAUT PAS en créer un"
warn "nouveau — ça créerait un second Cognito/AppSync/DynamoDB en doublon, déconnecté"
warn "des vraies données du pilote."
step "Quand la console demande l'environnement backend à utiliser, sélectionne 'dev'"
step "  (le seul qui doit apparaître dans la liste si l'app est bien reconnue — c'est"
step "  l'environnement déjà déployé, stack 'amplify-redlinkpwa-dev-f38d9')."
step "Si la console ne propose PAS de lier un environnement existant et veut en créer"
step "  un nouveau à la place, ARRÊTE-TOI ici et reviens m'en parler avant de continuer —"
step "  ça voudrait dire que la détection automatique n'a pas marché comme prévu."
if confirm "L'environnement 'dev' existant est bien sélectionné (pas un nouveau) ?"; then
  say "Bien reçu, on continue."
else
  warn "Arrête le wizard (Ctrl-C) et reviens en discuter avant de poursuivre."
fi
pause "Appuie sur Entrée pour continuer."

# ── Stage 4 ─────────────────────────────────────────────────────────────
stage "Paramètres de build (frontend Vite)"
say "Le repo n'a pas de amplify.yml custom — la console va essayer de détecter"
say "automatiquement les paramètres de build. Pour ce projet Vite :"
step "Build command attendu : 'npm run build' (ou 'npm ci && npm run build')."
step "Base directory / baseDirectory attendu : 'dist' (PAS 'build' — c'est le"
step "  défaut Create React App, pas Vite ; si la détection auto a mis 'build',"
step "  corrige-le manuellement en 'dist' dans l'éditeur de amplify.yml affiché)."
step "Si un artifact 'baseDirectory' différent est proposé, corrige-le avant de"
step "  continuer — un mauvais chemin fait échouer le déploiement silencieusement"
step "  côté contenu servi (build vert, page blanche)."
pause "Build command et baseDirectory vérifiés/corrigés ? Appuie sur Entrée."

# ── Stage 5 ─────────────────────────────────────────────────────────────
stage "Rôle de service (permissions)"
say "Amplify a besoin d'un rôle IAM de service pour construire et déployer."
step "Si la console propose de créer un nouveau rôle de service automatiquement,"
step "  accepte cette option par défaut (le plus simple pour un pilote)."
step "Si un rôle existant 'amplifyconsole-backend-role' ou équivalent est déjà"
step "  proposé dans la liste, tu peux le réutiliser à la place."
pause "Rôle de service configuré ? Appuie sur Entrée pour continuer."

# ── Stage 6 ─────────────────────────────────────────────────────────────
stage "Premier déploiement"
say "Dernière étape avant de lancer : relis l'écran récapitulatif affiché par la"
say "console (repo, branche, environnement backend 'dev', build settings) avant"
say "de cliquer 'Save and deploy'."
step "Clique 'Save and deploy'."
step "Attends que les 4 phases passent au vert : Provision → Build → Deploy → Verify."
note "Ça prend généralement 3 à 8 minutes pour un premier déploiement full-stack."
if confirm "Les 4 phases sont bien passées au vert (déploiement réussi) ?"; then
  say "Déploiement confirmé."
else
  warn "Regarde les logs de build dans la console (bouton 'Build details' sur la"
  warn "phase en échec) — reviens m'en parler avec le message d'erreur si besoin."
fi
pause "Appuie sur Entrée pour continuer."

# ── Stage 7 ─────────────────────────────────────────────────────────────
stage "URL finale et vérification du déploiement automatique"
say "Aucun domaine personnalisé n'est nécessaire pour ce pilote — l'URL par"
say "défaut fournie par Amplify (ex. https://main.xxxxxxxxxxxx.amplifyapp.com)"
say "suffit."
step "Copie l'URL affichée en haut de la page de l'app (celle de la branche 'main')."
ask AMPLIFY_HOSTING_URL "Colle l'URL de l'app déployée :"
write_env AMPLIFY_HOSTING_URL "$AMPLIFY_HOSTING_URL"
step "Vérifie que la branche 'main' affiche bien 'Auto-build' activé (icône ⚡ ou"
step "  toggle 'Enabled' à côté du nom de la branche dans la liste des branches) —"
step "  c'est ce qui déclenchera un déploiement à chaque futur push sur main."
step "Ouvre l'URL dans un navigateur et vérifie que la page d'accueil Redlink"
step "  s'affiche correctement (pas de page blanche, pas d'erreur de connexion"
step "  au backend)."
open_url "$AMPLIFY_HOSTING_URL"
pause "Page vérifiée dans le navigateur ? Appuie sur Entrée pour terminer."

finish

note "URL de l'app pilote : $AMPLIFY_HOSTING_URL"
note "Prochain déploiement automatique : au prochain push sur main."
